// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgungjbicqaafnzwwspd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndW5namJpY3FhYWZuend3c3BkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzUzMDIsImV4cCI6MjA2MzYxMTMwMn0.OiudOnCBDzB9KBEGx4h0cnM4998s1C13OV_rU_z3VNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);